// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"

	"github.com/larsartmann/templ-components/display"
	"github.com/larsartmann/templ-components/icons"
	"github.com/larsartmann/templ-components/utils"

	"github.com/larsartmann/templ-components/website/internal/build"
)

// StarsLabel renders the GitHub-stars CTA text ("1,234 Stars", or the static
// fallback when the build-time API lookup failed — same fail-soft behavior as
// the Astro hero).
func StarsLabel(stars int) string {
	if stars <= 0 {
		return "Star on GitHub"
	}
	return fmt.Sprintf("%s Stars", formatInt(stars))
}

// formatInt inserts thousands separators, matching the visual language of the
// library's CountBadge.
func formatInt(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	return string(out)
}

// Hero is the landing hero: pill, headline, CTAs, metric strip, and the
// highlighted code window with copy button (ported from HeroSection.astro).
// The metric numbers come from build.Stats — derived from the codebase at
// build time, never hand-typed.
func Hero(stats build.Stats, starsText string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"relative flex items-center justify-center overflow-hidden pt-36 pb-20\"><div class=\"absolute top-1/4 left-1/2 -translate-x-1/2 w-[900px] h-[500px] bg-accent/5 blur-[140px] rounded-full pointer-events-none\"></div><div class=\"relative max-w-3xl xl:max-w-7xl mx-auto px-6 text-center\"><div class=\"inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-border bg-bg-card-solid text-xs font-mono text-text-secondary mb-8 backdrop-blur-sm\"><span class=\"relative flex w-2 h-2\"><span class=\"animate-pulse-dot absolute inline-flex w-full h-full rounded-full bg-accent\"></span> <span class=\"relative inline-flex rounded-full w-2 h-2 bg-accent\"></span></span> Server-rendered UI for Go</div><h1 class=\"text-[clamp(2.75rem,8vw,4.5rem)] font-bold tracking-tighter leading-[1.05] mb-6 text-text-primary\">Build Go web apps<br>without a <span class=\"text-accent\">frontend framework</span>.</h1><p class=\"text-[clamp(1.0625rem,2.5vw,1.25rem)] text-text-secondary max-w-2xl mx-auto mb-10 leading-relaxed\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d server-rendered components for templ + HTMX + Tailwind CSS v4. Type-safe props, dark mode built-in, CSP-ready, zero Node.js.", stats.Components))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `website/internal/pages/hero.templ`, Line: 61, Col: 166}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p><div class=\"flex flex-col sm:flex-row items-center justify-center gap-3 mb-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = display.Button(display.ButtonProps{
			Text:    "Get Started",
			Href:    "/getting-started/installation",
			Variant: display.ButtonPrimary,
			Size:    display.ButtonSizeLG,
			Icon:    icons.Icon(icons.ArrowRight, "h-4 w-4"),
			BaseProps: utils.BaseProps{
				Class: "px-6 py-3 text-sm shadow-lg shadow-accent/20 hover:shadow-accent/30 hover:-translate-y-0.5",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = display.Button(display.ButtonProps{
			Text:     "Live Demo",
			Href:     DemoURL,
			External: true,
			Variant:  display.ButtonGhost,
			Size:     display.ButtonSizeLG,
			Icon:     icons.Icon(icons.Eye, "h-4 w-4"),
			BaseProps: utils.BaseProps{
				Class: "border border-border text-text-secondary hover:border-border-hover hover:text-text-primary hover:bg-transparent px-6 py-3.5 text-sm hover:-translate-y-0.5",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = display.Button(display.ButtonProps{
			Text:     starsText,
			Href:     GitHubURL,
			External: true,
			Variant:  display.ButtonGhost,
			Size:     display.ButtonSizeLG,
			Icon:     filledStarIcon("h-4 w-4"),
			BaseProps: utils.BaseProps{
				Class: "border border-border text-text-secondary hover:border-border-hover hover:text-text-primary hover:bg-transparent px-6 py-3.5 text-sm hover:-translate-y-0.5",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"flex items-center justify-center gap-6 md:gap-10 mb-16 max-w-xl mx-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = heroMetric(stats.Components, "Components").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"w-px h-10 bg-border shrink-0\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = heroMetric(stats.Icons, "SVG icons").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"w-px h-10 bg-border shrink-0\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = heroMetric(stats.Enums, "Typed enums").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"w-px h-10 bg-border shrink-0\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = heroMetric(stats.Modules, "Go modules").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"relative max-w-xl mx-auto\"><div class=\"absolute -inset-4 bg-gradient-to-r from-accent/8 via-transparent to-accent/8 rounded-2xl pointer-events-none\"></div><div class=\"relative rounded-xl border border-border bg-bg-code shadow-2xl overflow-hidden code-preview\"><div class=\"flex items-center gap-1.5 px-4 py-3 border-b border-border bg-bg-card-solid/50\"><span class=\"w-2.5 h-2.5 rounded-full bg-code-dot\"></span> <span class=\"w-2.5 h-2.5 rounded-full bg-code-dot\"></span> <span class=\"w-2.5 h-2.5 rounded-full bg-code-dot\"></span> <span class=\"ml-3 text-xs text-text-muted font-mono\">page.templ</span></div><pre tabindex=\"0\" class=\"p-5 text-left text-[0.8125rem] font-mono leading-[1.7] overflow-x-auto relative\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = highlightTempl(heroCode).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</pre><button class=\"absolute top-2 right-2 bg-code-inline-bg/80 border border-border rounded-md text-text-muted px-2 py-1 cursor-pointer text-xs font-mono hover:text-text-primary hover:border-border-hover transition-all duration-150 opacity-0 [.code-preview:hover_&]:opacity-100\" id=\"copy-btn\" data-code=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(heroCode)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `website/internal/pages/hero.templ`, Line: 117, Col: 314}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" aria-label=\"Copy code to clipboard\">Copy</button></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// heroMetric renders one number+label pair of the metric strip.
func heroMetric(value int, label string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"text-center\"><div class=\"text-xl font-bold text-text-primary font-mono\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", value))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `website/internal/pages/hero.templ`, Line: 127, Col: 87}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div><div class=\"text-xs text-text-muted mt-0.5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(label)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `website/internal/pages/hero.templ`, Line: 128, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
