package icons

// Name represents a named icon from the library
const (
	Home         = "home"
	Users        = "users"
	Folder       = "folder"
	Document     = "document"
	Search       = "search"
	Settings     = "settings"
	Chart        = "chart"
	Inbox        = "inbox"
	Check        = "check"
	X            = "x"
	Plus         = "plus"
	Minus        = "minus"
	ChevronRight = "chevron-right"
	ChevronLeft  = "chevron-left"
	ChevronDown  = "chevron-down"
	ChevronUp    = "chevron-up"
	ArrowRight   = "arrow-right"
	ArrowLeft    = "arrow-left"
	Refresh      = "refresh"
	ExternalLink = "external-link"
	Download     = "download"
	Upload       = "upload"
	Trash        = "trash"
	Edit         = "edit"
	Eye          = "eye"
	EyeOff       = "eye-off"
	Lock         = "lock"
	Unlock       = "unlock"
	Menu         = "menu"
	Bell         = "bell"
	Calendar     = "calendar"
	Clock        = "clock"
	Location     = "location"
	Phone        = "phone"
	Mail         = "mail"
	Globe        = "globe"
	Sun          = "sun"
	Moon         = "moon"
	Spinner      = "spinner"
	Exclamation  = "exclamation"
	Information  = "information"
	Question     = "question"
)
